"""Pydantic data models for Agent Smith.

Covers:
- StepMetrics: telemetry and traces for each Thought -> Code -> Observation cycle.
- SolutionOutput: final benchmark result contract and solution.json writer.
- SandboxConfig: sandbox execution limits and isolation policies.
- MBPPTaskInput & SWEBenchTaskInput: input problem loader definitions.
"""

from __future__ import annotations

import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

# Defaults for SandboxConfig
DEFAULT_AUTHORIZED_IMPORTS: list[str] = [
    "math",
    "math.*",
    "collections",
    "collections.*",
    "itertools",
    "re",
    "json",
    "typing",
    "typing.*",
    "functools",
    "operator",
    "heapq",
    "bisect",
    "copy",
    "string",
    "random",
    "datetime",
    "datetime.*",
    "array",
    "cmath",
]

DEFAULT_ALLOWED_DIRECTORIES: list[str] = [
    "/testbed",
    "/tmp/agent",
]


def current_iso_timestamp() -> str:
    """Return current UTC time in ISO 8601 format."""
    return datetime.now(timezone.utc).isoformat()


def validate_iso_8601_timestamp(v: str) -> str:
    """Validate that a string conforms to the ISO 8601 format."""
    if not isinstance(v, str) or not v.strip():
        raise ValueError("timestamp must be a non-empty ISO 8601 string")
    try:
        datetime.fromisoformat(v.replace("Z", "+00:00"))
    except Exception as exc:
        raise ValueError(f"Invalid ISO 8601 timestamp: '{v}'") from exc
    return v


# -----------------------------------------------------------------------------
# StepMetrics
# -----------------------------------------------------------------------------


class StepMetrics(BaseModel):
    """Telemetry and trace record for a single LLM-generate -> sandbox-execute cycle."""

    model_config = ConfigDict(extra="forbid")

    step: int = Field(..., ge=1, description="1-indexed iteration number of the cycle.")
    input_tokens: int = Field(..., ge=0, description="Tokens sent in the prompt for this step.")
    output_tokens: int = Field(..., ge=0, description="Tokens generated by the LLM for this step.")
    request_time_ms: float = Field(..., ge=0.0, description="LLM call latency in milliseconds.")
    timestamp: str = Field(
        default_factory=current_iso_timestamp,
        description="ISO 8601 timestamp when this step completed.",
    )
    api_url: str = Field(default="", description="Endpoint URL of the LLM provider used.")
    model_name: str = Field(default="", description="Model identifier used for this step.")
    llm_output: str = Field(default="", description="Raw LLM text response before code extraction.")
    sandbox_input: str = Field(default="", description="Extracted code sent to the sandbox.")
    sandbox_output: str = Field(
        default="", description="Sandbox execution result (stdout/stderr/errors)."
    )
    retries: int = Field(
        default=0,
        ge=0,
        description="Number of retries triggered for this step (due to rate limits, timeouts, etc.).",
    )

    @field_validator("timestamp")
    @classmethod
    def _validate_timestamp(cls, v: str) -> str:
        return validate_iso_8601_timestamp(v)


# -----------------------------------------------------------------------------
# SolutionOutput & Writer
# -----------------------------------------------------------------------------


class SolutionOutput(BaseModel):
    """Final solution output artifact (solution.json)."""

    model_config = ConfigDict(extra="forbid")

    task_id: str = Field(..., description="Unique identifier of the evaluated task.")
    benchmark: Literal["mbpp", "swebench"] = Field(
        ..., description="Benchmark type ('mbpp' or 'swebench')."
    )
    success: bool = Field(
        ..., description="Whether the task was solved successfully according to evaluation."
    )
    solution: str = Field(
        default="",
        description="The submitted solution (MBPP: Python function code; SWE-bench: git patch).",
    )
    iterations: int = Field(
        ..., ge=0, description="Total number of agent loop iterations executed."
    )
    total_requests: int = Field(..., ge=0, description="Total number of LLM API requests made.")
    total_input_tokens: int = Field(
        ..., ge=0, description="Total input/prompt tokens consumed across all steps."
    )
    total_output_tokens: int = Field(
        ..., ge=0, description="Total output/completion tokens consumed across all steps."
    )
    total_time_seconds: float = Field(
        ..., ge=0.0, description="Total wall-clock duration of the run in seconds."
    )
    steps: list[StepMetrics] = Field(
        default_factory=list, description="Ordered list of step telemetry records."
    )
    system_prompt: str = Field(
        default="", description="Full system prompt supplied to the agent for provenance."
    )
    error: str | None = Field(
        default=None,
        description="Error message if the agent aborted or encountered an unrecoverable failure.",
    )
    timestamp: str = Field(
        default_factory=current_iso_timestamp,
        description="ISO 8601 timestamp when this solution was finalized.",
    )

    @field_validator("task_id", mode="before")
    @classmethod
    def _normalize_task_id(cls, v: Any) -> str:
        if isinstance(v, bool):
            raise ValueError("task_id cannot be a boolean")  # noqa: TRY004
        if isinstance(v, (int, str)):
            s = str(v).strip()
            if not s:
                raise ValueError("task_id cannot be empty")
            return s
        raise ValueError(f"task_id must be a string or integer, got {type(v).__name__}")

    @field_validator("timestamp")
    @classmethod
    def _validate_timestamp(cls, v: str) -> str:
        return validate_iso_8601_timestamp(v)

    def write_to_file(self, path: Path | str, indent: int = 2) -> Path:
        """Write this SolutionOutput atomically to a JSON file."""
        return write_solution_json(self, path, indent=indent)


def write_solution_json(
    solution: SolutionOutput,
    path: Path | str,
    indent: int = 2,
) -> Path:
    """Atomically write SolutionOutput to the destination path.

    Uses a temporary file in the same directory and replaces the target file,
    ensuring solution.json is never corrupted by partial writes even on crash or abort.

    Args:
        solution: SolutionOutput instance to write.
        path: Destination file path.
        indent: Indentation level for pretty-printing JSON.

    Returns:
        Path to the written file.
    """
    target = Path(path).resolve()
    target.parent.mkdir(parents=True, exist_ok=True)

    data = solution.model_dump_json(indent=indent)

    tmp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            dir=target.parent,
            prefix=f".{target.name}.",
            suffix=".tmp",
            delete=False,
            encoding="utf-8",
        ) as tmp_file:
            tmp_path = Path(tmp_file.name)
            tmp_file.write(data)
            tmp_file.flush()
            os.fsync(tmp_file.fileno())
        tmp_path.replace(target)
    except Exception:
        if tmp_path is not None and tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise

    return target


# -----------------------------------------------------------------------------
# SandboxConfig
# -----------------------------------------------------------------------------


class SandboxConfig(BaseModel):
    """Configuration for the secure code execution sandbox."""

    model_config = ConfigDict(extra="forbid")

    authorized_imports: list[str] = Field(
        default_factory=lambda: list(DEFAULT_AUTHORIZED_IMPORTS),
        description="List of allowed import names (e.g., ['math', 'json']). Glob patterns supported.",
    )
    allowed_directories: list[str] = Field(
        default_factory=lambda: list(DEFAULT_ALLOWED_DIRECTORIES),
        description="List of filesystem paths the sandbox can access (e.g., ['/testbed', '/tmp/agent']).",
    )
    max_execution_time_seconds: int = Field(
        default=30,
        gt=0,
        description="Maximum wall-clock time in seconds for a single sandbox execution.",
    )
    max_memory_mb: int = Field(
        default=512,
        gt=0,
        description="Maximum memory in megabytes for sandbox execution.",
    )

    @classmethod
    def from_file(cls, path: Path | str) -> SandboxConfig:
        """Load and validate SandboxConfig from a JSON file."""
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"Sandbox configuration file not found: {path}")
        with open(file_path, "r", encoding="utf-8") as f:
            return cls.model_validate_json(f.read())

    def to_json(self, indent: int = 2) -> str:
        """Serialize configuration to a formatted JSON string."""
        return self.model_dump_json(indent=indent)


# -----------------------------------------------------------------------------
# Task Input Loaders (MBPP & SWE-bench)
# -----------------------------------------------------------------------------


class MBPPTaskInput(BaseModel):
    """Input structure for an MBPP benchmark task loaded from --task-file JSON."""

    model_config = ConfigDict(extra="forbid", strict=True)

    task_id: int | str = Field(..., description="Unique MBPP task identifier (e.g. 11).")
    task_definition: str = Field(..., description="Natural language problem statement.")
    function_definition: str = Field(..., description="Expected function signature or stub.")
    test_imports: list[str] = Field(
        default_factory=list, description="Import statements required by the unit tests."
    )
    test_list: list[str] = Field(
        ..., min_length=1, description="List of assert statements verifying the solution."
    )

    @classmethod
    def from_file(cls, path: Path | str) -> MBPPTaskInput:
        """Load and validate MBPPTaskInput from a JSON file."""
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"MBPP task file not found: {path}")
        with open(file_path, "r", encoding="utf-8") as f:
            return cls.model_validate_json(f.read())


class SWEBenchTaskInput(BaseModel):
    """Input structure for a SWE-bench task loaded from --task-file JSON."""

    model_config = ConfigDict(extra="forbid", strict=True)

    instance_id: str = Field(
        ..., description="SWE-bench instance identifier (e.g. 'sympy__sympy-14711')."
    )
    problem_statement: str = Field(..., description="Problem description from the repository task.")
    docker_image: str = Field(..., description="Name or tag of the Docker image for this instance.")
    eval_script: str = Field(..., description="Evaluation script / command to verify the fix.")
    hints_text: str = Field(
        default="", description="Hints or discussion text associated with the task."
    )
    repo: str = Field(..., description="Target repository name (e.g. 'sympy/sympy').")

    @classmethod
    def from_file(cls, path: Path | str) -> SWEBenchTaskInput:
        """Load and validate SWEBenchTaskInput from a JSON file."""
        file_path = Path(path)
        if not file_path.is_file():
            raise FileNotFoundError(f"SWE-bench task file not found: {path}")
        with open(file_path, "r", encoding="utf-8") as f:
            return cls.model_validate_json(f.read())


def load_task_input(
    path: Path | str,
    benchmark: Literal["mbpp", "swebench"],
) -> MBPPTaskInput | SWEBenchTaskInput:
    """Helper to load either MBPPTaskInput or SWEBenchTaskInput based on benchmark type."""
    if benchmark == "mbpp":
        return MBPPTaskInput.from_file(path)
    elif benchmark == "swebench":
        return SWEBenchTaskInput.from_file(path)
    else:
        raise ValueError(f"Unknown benchmark: '{benchmark}'. Expected 'mbpp' or 'swebench'.")
